In [1]:
#Importing one_hot for one_hot_encoding
from keras.preprocessing.text import one_hot

In [2]:
#Sample Sentences
sent=['I am Srikanth',
'I am developer',
'I write code',
'lets build Logic',
'we will learn DL'
]

In [3]:
#Dictionary size
voc_size = 10000

In [4]:
# one_hot representation of each word in sample sentences
vec_rep = [one_hot(words, voc_size) for words in sent]

In [5]:
print(vec_rep)

[[6380, 648, 5884], [6380, 648, 6816], [6380, 8430, 7285], [971, 936, 3688], [7650, 7116, 5481, 2949]]


In [6]:
#Importing embedding layers fro embedding encoded words and pad_sequences to make sure every word of equal length 

from keras.layers import embeddings
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np

In [8]:
# making the sentence length as 6 
sent_length = 6
embedded_docs = pad_sequences(vec_rep, padding='pre', maxlen=sent_length)

In [9]:
print(embedded_docs)

[[   0    0    0 6380  648 5884]
 [   0    0    0 6380  648 6816]
 [   0    0    0 6380 8430 7285]
 [   0    0    0  971  936 3688]
 [   0    0 7650 7116 5481 2949]]


In [10]:
# Taking features as 10 in Dictionary for every sentence 
features=10

In [12]:
# Building a Model for embedding the one_hot encoded vectors
model = Sequential()
model.add(embeddings.Embedding(voc_size, features, input_length=sent_length))
model.compile('adam', 'mse')

In [13]:
# In the builded model, making the 10 features for each and every sentence

model.predict(embedded_docs)

array([[[-0.04390356,  0.01570574, -0.01649676, -0.02122932,
         -0.01731436, -0.04335489, -0.01747258,  0.04188463,
          0.02458714,  0.04610591],
        [-0.04390356,  0.01570574, -0.01649676, -0.02122932,
         -0.01731436, -0.04335489, -0.01747258,  0.04188463,
          0.02458714,  0.04610591],
        [-0.04390356,  0.01570574, -0.01649676, -0.02122932,
         -0.01731436, -0.04335489, -0.01747258,  0.04188463,
          0.02458714,  0.04610591],
        [-0.00217662, -0.04711014, -0.01810952,  0.04749307,
         -0.04388682, -0.03060691,  0.01603306,  0.02828466,
          0.00059776,  0.04565731],
        [-0.02973704, -0.02209522,  0.01364113, -0.01348581,
         -0.02635716,  0.03757114,  0.04936847,  0.00423645,
          0.04024489, -0.04025482],
        [-0.00702215,  0.00256761,  0.00888358,  0.00353225,
         -0.04979674,  0.01262219, -0.0049162 ,  0.0201647 ,
          0.0292499 ,  0.00157403]],

       [[-0.04390356,  0.01570574, -0.01649676, -0

In [14]:
# 1st sentence one_hot encoded vector of sample sentences
embedded_docs[0]

array([   0,    0,    0, 6380,  648, 5884], dtype=int32)

In [15]:
# In the builded model, making the 10 features for very first sentence.
model.predict(embedded_docs[0])

array([[-0.04390356,  0.01570574, -0.01649676, -0.02122932, -0.01731436,
        -0.04335489, -0.01747258,  0.04188463,  0.02458714,  0.04610591],
       [-0.04390356,  0.01570574, -0.01649676, -0.02122932, -0.01731436,
        -0.04335489, -0.01747258,  0.04188463,  0.02458714,  0.04610591],
       [-0.04390356,  0.01570574, -0.01649676, -0.02122932, -0.01731436,
        -0.04335489, -0.01747258,  0.04188463,  0.02458714,  0.04610591],
       [-0.00217662, -0.04711014, -0.01810952,  0.04749307, -0.04388682,
        -0.03060691,  0.01603306,  0.02828466,  0.00059776,  0.04565731],
       [-0.02973704, -0.02209522,  0.01364113, -0.01348581, -0.02635716,
         0.03757114,  0.04936847,  0.00423645,  0.04024489, -0.04025482],
       [-0.00702215,  0.00256761,  0.00888358,  0.00353225, -0.04979674,
         0.01262219, -0.0049162 ,  0.0201647 ,  0.0292499 ,  0.00157403]],
      dtype=float32)